# {
#     "rules": {
#         "no-unused-vars": "off"
#     }
# }

env:
  es2020: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - jest
  - '@typescript-eslint'
extends:
#   - eslint:recommended
#   - plugin:@typescript-eslint/eslint-recommended
#   - plugin:@typescript-eslint/recommended
#   - plugin:jest/recommended
  - prettier
rules:
  '@typescript-eslint/no-empty-interface': off